- name: play1
  gather_facts: no
  hosts: servera.lab.example.com
  vars_files:
  - vars/myvar1.yaml
  - vars/myvar2.yaml
  - vars/myvar3.yaml
  - vars/myvar4.yaml
  - vars/myvar5.yaml
  tasks:
  - debug:
      msg:
        - "{{ user1 }} password is {{ pass1 }}"
        - "{{ user2 }} password is {{ pass2 }}"
        - "{{ user3 }} password is {{ pass3 }}"
        - "{{ user4 }} password is {{ pass4 }}"
        - "{{ user5 }} password is {{ pass5 }}"
        - "{{ ansible_distribution }}"
        - "{{ ansible_facts['distribution'] }}"
